// src/app/testimonials/testimonials.component.ts
import { Component, OnInit } from '@angular/core';

interface Testimonial {
  name: string;
  about: string;
  message: string;
  photoUrl: string;
}

@Component({
  selector: 'app-testimonials',
  templateUrl: './testimonials.component.html',
  styleUrls: ['./testimonials.component.scss'],
})
export class TestimonialsComponent implements OnInit {
  testimonials: Testimonial[] = [
    {
      name: 'Tarini Charana Mishra',
      about: 'Professor, SIT Bhubaneswar',
      message: `Sameer was an exceptional student in terms of intellectual
      capability and his interest in development. He has
      undertaken projects in field of IOT and Web development. He
      was a technology enthusiast as well as a good teacher at
      college mentoring his fellows and junior students.`,
      photoUrl: '../../assets/img/testimonial/tarini.jpeg',
    },
    {
      name: 'Alok Patnaik',
      about: 'Professor &amp; Astronomy Researcher at KIIT',
      message: `It's always a pleasure to discuss ideas with him for his
      in-depth knowledge of the subject. He is a thorough
      professional in his dealings - punctual, focused, sincere
      and dedicated. He is adventurous, would not hesitate to get
      in to new ideas and new technologies. He is an asset to any
      team he works with.`,
      photoUrl: '../../assets/img/testimonial/alok.jpeg',
    },
    {
      name: 'Nirmal Hota',
      about: 'Project Manager, Mindfire Solutions',
      message: `Sameer is a very technology passionate guy I have ever met.
      He has started his career in my team as an intern to fresher
      to a fully grown developer. I witnessed his quick growth and
      maturity of technology in him.`,
      photoUrl: '../../assets/img/testimonial/nirmal.jpeg',
    },
    {
      name: 'Rishav Kumar',
      about: 'Software Engineer, Big Binary',
      message: `Sameer's multitasking ability was unlike I've seen before.
      I've worked with many developers but when it comes to Ruby
      on Rails, he's really good at it. In short span of time, he
      has gained ample of experience in Ruby on Rails. Sameer will
      be a valuable asset to any company.`,
      photoUrl: '../../assets/img/testimonial/rishav.jpeg',
    },
    {
      name: 'JP Mohapatra',
      about: 'Sr.Software engineer at Mindfire solutions',
      message: `He proves his uniqueness and dedication each time he get a
      chance to resolve complex issues or handling the client.
      Never forgets to add some extra efforts towards sharing the
      same knowledge among team mates. It was a pleasure working
      with Sameer and wish him a great future ahead.`,
      photoUrl: '../../assets/img/testimonial/jyoti.jpeg',
    },
    {
      name: 'Sarthak Sahoo',
      about: 'Systems Engineer, Infosys',
      message: `Sameer is a very good learner of new technologies and worked
      in different projects with new technologies. He is a very
      good team player and his commitment for a work is one of the
      best thing.`,
      photoUrl: '../../assets/img/testimonial/sarthak.jpeg',
    },
  ];

  constructor() {}

  ngOnInit(): void {}
}

<section id="testimonials" class="testimonials section-bg">
  <div class="container">
    <div class="section-title">
      <h2>Testimonials</h2>
      <p class="text-muted">Sourced from LinkedIn</p>
    </div>

    <div id="carouselExampleCaptions" class="carousel carousel-dark slide " data-bs-ride="false">
      <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active"
          aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1"
          aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2"
          aria-label="Slide 3"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="3"
          aria-label="Slide 4"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="4"
          aria-label="Slide 5"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="5"
          aria-label="Slide 6"></button>
      </div>
      <div class="carousel-inner">
        <div class="carousel-item active">
          <div class="carousel-caption d-none d-md-block">
            <img src={{testimonials[0].photoUrl}} class="rounded-circle" alt={{testimonials[0].name}}>
            <h4 class="name mt-2">{{testimonials[0].name}}</h4>
            <p class="name"></p>
            <p class="text-secondary">
              {{testimonials[0].message}}
            </p>
          </div>
        </div>
        <div class="carousel-item" *ngFor="let testimonial of testimonials.slice(1)">
          <div class="carousel-caption d-none d-md-block">
            <img src={{testimonial.photoUrl}} class="rounded-circle" alt={{testimonial.name}}>
            <h4 class="name mt-2">{{testimonial.name}}</h4>
            <p class="name">{{testimonial.about}}</p>
            <p class="text-secondary">
              {{testimonial.message}}
            </p>
          </div>
        </div>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions"
        data-bs-slide="prev">
        <span class="carousel-control carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions"
        data-bs-slide="next">
        <span class="carousel-control carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
  </div>
</section>

// src/app/about/blocks/testimonials.tsx
import './testimonials.scss';

export function Testimonials() {
  const testimonials = [
    {
      author: 'Tarini Charana Mishra',
      designation: 'Silicon Tech Lab, Bhubaneswar',
      content: `Sameer was an exceptional student in terms of intellectual capability and his interest in development. He has undertaken
        projects in field of IOT and Web development. He was a technology enthusiast as well as a good teacher at college mentoring
        his fellows and junior students.`
    },
    {
      author: 'Sarthak Sahoo',
      designation: 'Software Engineer at Cisco',
      content: `Sameer is a very good learner of new technologies and worked in different projects with new technologies. He is a very
        good team player and his commitment for a work is one of the best thing.`
    },
    {
      author: 'Alok Patnaik',
      designation: 'Professor, Astronomy Researcher at KIIT',
      content: `It's always a pleasure to discuss ideas with him for his in-depth knowledge of the subject. He is a thorough professional
        in his dealings - punctual, focused, sincere and dedicated. He is adventurous, would not hesitate to get in to new ideas
        and new technologies. He is an asset to any team he works with.`
    },
    {
      author: 'Nirmal Hota',
      designation: 'Director | Co-founder | CEO',
      content: `Sameer is a very technology passionate guy I have ever met. He has started his career in my team as an intern to fresher
        to a fully grown developer. I witnessed his quick growth and maturity of technology in him.`
    },
    {
      author: 'Rishav Kumar',
      designation: 'Software Engineer, Big Binary',
      content: `Sameer's multitasking ability was unlike I've seen before. I've worked with many developers but when it comes to Ruby on
        Rails, he's really good at it. In short span of time, he has gained ample of experience in Ruby on Rails. Sameer will be a
        valuable asset to any company.`
    },
    {
      author: 'JP Mohapatra',
      designation: 'Sr. Software engineer',
      content: `He proves his uniqueness and dedication each time he get a chance to resolve complex issues or handling the client. Never
        forgets to add some extra efforts towards sharing the same knowledge among team mates. It was a pleasure working with
        Sameer and wish him a great future ahead.`
    }
  ];

  return (
    <>
      <h1 className="font-acorn text-primary mt-5 mb-0 my-journey-title">Testimonials</h1>
      <small className="mb-5 text-primary source-linkedin">Sourced from LinkedIn</small>
      <div className="row testimonial-grid container gx-4 gy-3">
        {testimonials.map(testimonial => (
          <div className="col-sm-12 col-md-6" key={testimonial.author}>
            <div className="testimonial-card rounded-4">
              <p className="content">{testimonial.content}</p>
              <small className="mt-auto">
                - {testimonial.author}, {testimonial.designation}
              </small>
            </div>
          </div>
        ))}
      </div>
    </>
  );
}
