// src/app/blog/page.tsx
import Link from 'next/link';
import './blog.scss';

interface Article {
  canonical_url: string;
  cover_image: string;
  title: string;
}

async function fetchArticles(): Promise<Article[]> {
  const res = await fetch('https://dev.to/api/articles/latest?username=sameer1612');
  const json_res = await res.json();

  return json_res.map((article: any) => {
    return {
      canonical_url: article.canonical_url,
      cover_image: article.cover_image,
      title: article.title
    } as Article;
  });
}

export default async function Blog() {
  const articles = await fetchArticles();

  return (
    <main>
      <div className="text-center">
        <h1 className="title-1 text-primary my-5">Blog</h1>
        <div className="row container-fluid mx-auto my-5">{articles.map(article => ArticleCard(article))}</div>
      </div>
    </main>
  );
}

function ArticleCard(article: Article) {
  return (
    <div className="col-lg-4 col-md-6 col-sm-12 my-2">
      <div className="card rounded blog-card">
        <Link href={article.canonical_url} className="card-link" target="blank">
          <img className="card-img rounded-0" src={article.cover_image} alt={article.title}></img>
          <div className="card-body">
            <p className="card-title">{article.title}</p>
          </div>
        </Link>
      </div>
    </div>
  );
}

// src/app/blog/blog.component.ts
import { Component, OnInit } from '@angular/core';

export interface Article {
  canonical_url: string;
  cover_image: string;
  title: string;
}

@Component({
  selector: 'app-blog',
  templateUrl: './blog.component.html',
  styleUrls: ['./blog.component.scss'],
})
export class BlogComponent implements OnInit {
  articles: Article[];

  constructor() {
    this.articles = [];
  }

  ngOnInit(): void {
    fetch('https://dev.to/api/articles/latest?username=sameer1612')
      .then((res) => res.json())
      .then((data) => {
        this.articles = data.map((article: any) => {
          return {
            canonical_url: article.canonical_url,
            cover_image: article.cover_image,
            title: article.title,
          } as Article;
        });
      });
  }
}

<section id="blog" class="blog section-bg">
  <div class="container">
    <div class="section-title">
      <h2>Articles</h2>
      <p>
        If you know something but can't explain to someone else, its
        doesn't count. Whenever I write something, its not for someone
        else but for my one month earlier version completely unaware of
        how cool that tech is.
      </p>
    </div>

    <div class="row" data-aos="fade-up">
      <div class="col-lg-12 d-flex justify-content-center">
        <ul id="blog-flters">
          <li data-filter="*" class="filter-active">All</li>
          <li data-filter=".filter-web">Tech</li>
        </ul>
      </div>
    </div>
  </div>
  <div id="articles-container" class="row articles-container">
    <div class="col-lg-4 col-md-6 article filter-web" *ngFor="let article of articles">
      <div class="text-center">
        <a target="_blank" href="{{article.canonical_url}}">
          <img src="{{article.cover_image}}" class="img-fluid rounded" style="object-fit: contain;"
            alt="{{article.title}}" />
          <p class="text-secondary mt-2">{{article.title}}</p>
        </a>
      </div>
    </div>
  </div>
</section>
